config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  root to: 'dashboard#index', constraints: lambda { |request| Profile.first && !Profile.first.secure_data_viewing }
  root to: 'about#index', as: :unauthenticated_root

  namespace :api, :defaults => {format: 'json'} do
    namespace :v1 do
      resources :sites
      resources :data, only: [:index, :show]
    end
  end

  get '/bulk_download'            , to: 'bulk_download#index'
  get '/bulk_download/download'  , to: 'bulk_download#download'
  delete '/bulk_download/delete'  , to: 'bulk_download#destroy'
  post '/bulk_download'           , to: 'bulk_download#create'

  resources :dashboard
  resources :data, only: :index
  resources :influxdb_tags
  resources :linked_data, only: [:index, :edit, :update, :show]
  resources :measured_properties
  resources :site_types
  resources :topic_categories
  resources :units

  

  resources :about, only: :index do
    collection do
      get :data_urls
    end
  end

  resources :instruments do
    member do
      get :live
    end

    collection do
      get :duplicate
      get :live
      get :simulator
    end
  end

  resources :measurements, except: [:index, :show, :new, :create, :update, :edit, :destroy] do
    collection do
      get  :url_create
      post :delete_test
    end
  end

  resources :monitor do
    collection do
      get :live
    end
  end

  resources :profiles, only: [:index, :create, :backup, :restore] do
    collection do
      get :export_configuration
      get :import_configuration
      post :import_configuration

      get :export_influxdb
      get :import_influxdb
      post :import_influxdb

      post :test_sending_email
    end
  end

  resources :sites do
    collection do
      get :map
      get :map_markers_geojson
    end

    member do
      get :map_balloon_json
    end
  end

  resources :users do
    get :assign_api_key
  end

  resources :vars do
    collection do
      get :autocomplete_measured_property_label
      get :autocomplete_unit_name
    end
  end

end

app/controllers/site_types_controller.rb
class SiteTypesController < ApplicationController
  load_and_authorize_resource

	def index
  end

  def show
  end
end

app/helpers/site_types_helper.rb
module SiteTypesHelper
end

app/views/site_types/index.html.haml
%p#notice= notice

%h1 
  .center
    Site Types


.row-fluid.variable
  .col-sm-1
    %strong
      Id

  .col-sm-3
    %strong
      Name

  .col-sm-8
    %strong
      Definition

.clear

- @site_types.each do |type|

  .row-fluid.variable
    .col-sm-1
      .variable_header
        Id:
      = type.id

    .col-sm-3
      .variable_header
        Start:
      = type.name

    .col-sm-8
      .variable_header
        Definition:
      = type.definition
  .clear

%br
        

app/views/site_types/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @site_type.name
%p
  %strong Definition:
  = @site_type.definition

= link_to 'Back', site_types_path