config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  root to: 'dashboard#index', constraints: lambda { |request| Profile.first && !Profile.first.secure_data_viewing }
  root to: 'about#index', as: :unauthenticated_root

  namespace :api, :defaults => {format: 'json'} do
    namespace :v1 do
      resources :sites
      resources :data, only: [:index, :show]
    end
  end

  get '/bulk_download'            , to: 'bulk_download#index'
  get '/bulk_download/download'  , to: 'bulk_download#download'
  delete '/bulk_download/delete'  , to: 'bulk_download#destroy'
  post '/bulk_download'           , to: 'bulk_download#create'

  resources :dashboard
  resources :data, only: :index
  resources :influxdb_tags
  resources :linked_data, only: [:index, :edit, :update, :show]
  resources :measured_properties
  resources :site_types
  resources :topic_categories
  resources :units

  

  resources :about, only: :index do
    collection do
      get :data_urls
    end
  end

  resources :instruments do
    member do
      get :live
    end

    collection do
      get :duplicate
      get :live
      get :simulator
    end
  end

  resources :measurements, except: [:index, :show, :new, :create, :update, :edit, :destroy] do
    collection do
      get  :url_create
      post :delete_test
    end
  end

  resources :monitor do
    collection do
      get :live
    end
  end

  resources :profiles, only: [:index, :create, :backup, :restore] do
    collection do
      get :export_configuration
      get :import_configuration
      post :import_configuration

      get :export_influxdb
      get :import_influxdb
      post :import_influxdb

      post :test_sending_email
    end
  end

  resources :sites do
    collection do
      get :map
      get :map_markers_geojson
    end

    member do
      get :map_balloon_json
    end
  end

  resources :users do
    get :assign_api_key
  end

  resources :vars do
    collection do
      get :autocomplete_measured_property_label
      get :autocomplete_unit_name
    end
  end

end

app/controllers/linked_data_controller.rb
class LinkedDataController < ApplicationController
  authorize_resource

  def index
    @linked_datum = LinkedDatum.first

    if @linked_datum.nil?
      LinkedDatum.initialize(root_url)
      @linked_datum = LinkedDatum.first
    end

    respond_to do |format|
      format.html
      format.json { render json: @linked_datum.to_json_ld }
    end
  end

  def show
    redirect_to linked_data_path
  end

  def create
  end

  def edit
    @linked_datum = LinkedDatum.first
  end

  def update
    @linked_datum = LinkedDatum.first

    respond_to do |format|
      if @linked_datum.update(linked_datum_params)
        format.html { redirect_to linked_datum_path, notice: 'JSON-LD information was successfully updated' }
      else
        format.html { render :edit }
      end
    end
  end

private
  def linked_datum_params
    params.require(:linked_datum).permit(:name, :description, :keywords, :license, :doi)
  end
end

app/views/linked_data/_form.html.haml
= form_for @linked_datum do |f|
  - if @linked_datum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@linked_datum.errors.count, "error")} prohibited dat from being saved:"
      %ul
        - @linked_datum.errors.full_messages.each do |message|
          %li= message

  .line
    .title
      = f.label :name
    .field
      = f.text_area :name, class: 'form-control'
  .line
    .title
      = f.label :description
    .field
      = f.text_area :description, rows: 10, class: 'form-control'
  .line
    .title
      = f.label :keywords
    .field
      Comma separated list of keywords to aid searching for your dataset
      = f.text_area :keywords, rows:3, class: 'form-control'
  .line
    .title
      = f.label :dataset_url, 'URL'
    .field
      URL where your site is located, e.g. http://portal.chordsrt.com
      = f.text_field :dataset_url, class: 'form-control'
  .line
    .title
      = f.label :license
    .field
      License for your dataset, such as CC for Creative Commons or a URL to license text
      = f.text_field :license, class: 'form-control'
  .line
    .title
      = f.label :doi, 'DOI'
    .field
      DOI for your dataset in the format: 10.5065/D6V1236Q  (this is the CHORDS DOI)
      = f.text_field :doi, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-md btn-primary'

app/views/linked_data/edit.html.haml
%h1 Editing JSON-LD Information
%br
%div.row
  %div.col-lg-9.col-md-11
    = render 'form'
%br
= link_to 'Back', linked_data_path

app/views/linked_data/index.html.haml
%h2 JSON-LD Configuration

%p
  JSON-LD helps data discovery by providing a uniform metadata interface for search engines to parse, such as
  EarthCube's Project 418. Refer to
  = link_to 'https://www.earthcube.org/group/project-418', 'https://www.earthcube.org/group/project-418'
  for more information.

%br/

%p
  %b Name:
  = @linked_datum.name
%p
  %b Description:
  = @linked_datum.description
%p
  %b Keywords:
  = @linked_datum.keywords
%p
  %b URL:
  = @linked_datum.dataset_url
%p
  %b License:
  = @linked_datum.license
%p
  %b DOI:
  = @linked_datum.doi

%br
- if can? :edit, LinkedDatum
  = button_to 'Edit', edit_linked_datum_path(@linked_datum), method: :get, class: 'btn btn-default btn-md'
%br
= link_to 'Back', profiles_path