config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  root to: 'dashboard#index', constraints: lambda { |request| Profile.first && !Profile.first.secure_data_viewing }
  root to: 'about#index', as: :unauthenticated_root

  namespace :api, :defaults => {format: 'json'} do
    namespace :v1 do
      resources :sites
      resources :data, only: [:index, :show]
    end
  end

  get '/bulk_download'            , to: 'bulk_download#index'
  get '/bulk_download/download'  , to: 'bulk_download#download'
  delete '/bulk_download/delete'  , to: 'bulk_download#destroy'
  post '/bulk_download'           , to: 'bulk_download#create'

  resources :dashboard
  resources :data, only: :index
  resources :influxdb_tags
  resources :linked_data, only: [:index, :edit, :update, :show]
  resources :measured_properties
  resources :site_types
  resources :topic_categories
  resources :units

  

  resources :about, only: :index do
    collection do
      get :data_urls
    end
  end

  resources :instruments do
    member do
      get :live
    end

    collection do
      get :duplicate
      get :live
      get :simulator
    end
  end

  resources :measurements, except: [:index, :show, :new, :create, :update, :edit, :destroy] do
    collection do
      get  :url_create
      post :delete_test
    end
  end

  resources :monitor do
    collection do
      get :live
    end
  end

  resources :profiles, only: [:index, :create, :backup, :restore] do
    collection do
      get :export_configuration
      get :import_configuration
      post :import_configuration

      get :export_influxdb
      get :import_influxdb
      post :import_influxdb

      post :test_sending_email
    end
  end

  resources :sites do
    collection do
      get :map
      get :map_markers_geojson
    end

    member do
      get :map_balloon_json
    end
  end

  resources :users do
    get :assign_api_key
  end

  resources :vars do
    collection do
      get :autocomplete_measured_property_label
      get :autocomplete_unit_name
    end
  end

end

app/models/site.rb
class Site < ApplicationRecord
  has_many :instruments, :dependent => :destroy
  belongs_to :site_type

  def self.initialize
  end

  def to_s
    name
  end

  def self.list_site_options
    Site.select("id, name").map {|site| [site.id, site.name] }
  end
end

app/controllers/api/v1/data_controller.rb
require 'zip'

module API
  module V1
    class DataController < ApplicationController
      respond_to :json


      def index
        auth = false
        instruments = nil

        if ['json', 'geojson', 'csv'].include?(params[:format])
          if @profile.secure_data_download
            authorize! :download, Instrument
            auth = true
          else
            auth = true
          end
        else
          render json: {errors: ['FAIL: Invalid format requested. JSON, GEOJSON, and CSV are supported.']}, status: :not_acceptable
          return
        end

        if !auth
          render json: {errors: ['FAIL: Not authorized to create measurements. Ensure secure key or api_key and email are present.']}, status: :unauthorized
          return
        end

        instruments = Instrument.accessible_by(current_ability)

        instruments = if params[:sensors]
                        instruments.where(sensor_id: params[:sensors].split(','))
                      elsif params[:instruments]
                        instruments.where(id: params[:instruments].split(',').map(&:to_i))
                      else
                        instruments
                      end

        # Determine the time range. Default to the most recent day
        end_time = Time.now
        start_time = end_time - 1.day

        if params[:start]
          start_time = Time.parse(params[:start])
        end

        if params[:end]
          end_time = Time.parse(params[:end])
        end

        # Check whether to include test data
        test_opts = params.has_key?(:include_test_data) ? :either : :not_test

        # Check number of points to download against max allowed
        points_count = GetTsCountMultiInst.call(TsPoint, instruments, start_time: start_time, end_time: end_time, find_test: test_opts)
        allowed_points_count = Profile.first.max_download_points

        if points_count > allowed_points_count
          render json: {errors: ["FAIL: Requested number of data points exceeds that allowed. Requested: #{points_count}  Allowed: #{allowed_points_count}"]}, status: 413
          return
        end

        # Get the time series points from the database
        ts_points  = GetTsPointsMultiInst.call(TsPoint, instruments, start_time: start_time, end_time: end_time, find_test: test_opts)

        # File name root
        file_root = "#{@profile.project}_multi_instrument_download"
        file_root = file_root.split.join

        respond_to do |format|
          format.json do
            render json: MakeGeoJsonFromTsPoints.call(ts_points, @profile, instruments)
          end

          format.geojson do
            ts_json = MakeGeoJsonFromTsPoints.call(ts_points, @profile, instruments)
            send_data ts_json, filename: file_root + '.geojson'
          end

          format.csv do
            if instruments.count == 1
              varnames_by_id = {}
              instrument = instruments.first
              Var.all.where("instrument_id = #{instrument.id}").each {|v| varnames_by_id[v[:id]] = v[:name]}
              ts_csv = MakeGeoCsvFromTsPoints.call(ts_points, Array.new, varnames_by_id, instrument, request.host, Profile.first)

              file_root = "#{@profile.project}_#{instrument.site.name}_#{instrument.name}"
              file_root = file_root.split.join

              send_data ts_csv, filename: file_root + '.csv'
            else
              compressed_filestream = Zip::OutputStream.write_buffer(::StringIO.new('')) do |zos|
                instruments.each do |instrument|
                  varnames_by_id = {}
                  Var.all.where("instrument_id = #{instrument.id}").each {|v| varnames_by_id[v[:id]] = v[:name]}
                  csv = MakeGeoCsvFromTsPoints.call(ts_points.select{|point| point['inst'] == "#{instrument.id}"}, Array.new, varnames_by_id, instrument, request.host, Profile.first)

                  zos.put_next_entry "instrument_#{instrument.id}.csv"
                  zos.write csv
                end
              end

              send_data compressed_filestream.string, filename: "#{file_root}.zip"
            end
          end
        end
      end


      def show
        auth = false

        @instrument = Instrument.accessible_by(current_ability).where(id: params[:id]).first

        if ['csv', 'json', 'geojson', 'sensorml'].include?(params[:format])
          if @profile.secure_data_download
            authorize! :download, @instrument
            auth = true
          else
            auth = true
          end
        else
          render json: {errors: ['FAIL: Invalid format requested. CSV, JSON, and GEOJSON are supported.']}, status: :not_acceptable
          return
        end

        if !auth
          render json: {errors: ['FAIL: Not authorized to create measurements. Ensure secure key or api_key and email are present.']}, status: :unauthorized
          return
        end

        # Get the timezone name and offset in minutes from UTC.
        @tz_name, @tz_offset_mins = ProfileHelper::tz_name_and_tz_offset

        # Determine the time range. Default to the most recent day
        end_time = Time.now
        start_time = end_time - 1.day

        if params.key?(:last)
          start_time = @instrument.point_time_in_ms("last")
          end_time = start_time
        else
          # See if we have the start and end parameters
          if params.key?(:start)
            start_time = Time.parse(params[:start])
          end

          if params.key?(:end)
            end_time = Time.parse(params[:end])
          end
        end

        # Check whether to include test data
        test_opts = params.has_key?(:test) ? :either : :not_test

        # Check number of points to download against max allowed
        points_count = GetTsCountMultiInst.call(TsPoint, [@instrument.id], start_time: start_time, end_time: end_time, find_test: test_opts)
        allowed_points_count = Profile.first.max_download_points

        if points_count > allowed_points_count
          render json: {errors: ["FAIL: Requested number of data points exceeds that allowed. Requested: #{points_count}  Allowed: #{allowed_points_count}"]}, status: 413
          return
        end

        # Get the time series points from the database
        ts_points  = GetTsPointsMultiInst.call(TsPoint, [@instrument.id], start_time: start_time, end_time: end_time, find_test: test_opts)

        # File name root
        file_root = "#{@profile.project}_#{@instrument.site.name}_#{@instrument.name}"
        file_root = file_root.split.join

        respond_to do |format|
          format.csv do
            varnames_by_id = {}
            Var.all.where("instrument_id = #{@instrument.id}").each {|v| varnames_by_id[v[:id]] = v[:name]}
            ts_csv = MakeGeoCsvFromTsPoints.call(ts_points, Array.new, varnames_by_id, @instrument, request.host, Profile.first)
            send_data ts_csv, filename: file_root + '.csv'
          end

          format.json do
            render json: MakeGeoJsonFromTsPoints.call(ts_points, @profile, @instrument)
          end

          format.geojson do
            ts_json = MakeGeoJsonFromTsPoints.call(ts_points, @profile, @instrument)
            send_data ts_json, filename: file_root + '.geojson', type: 'application/json'
          end
        end
      end

    private
      def data_params
        params.require(:data).permit(:instruments, :start, :end)
      end
    end
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController

  def index
    authorize! :read, :data

    @sites = Site.accessible_by(current_ability)
    @instruments = Instrument.accessible_by(current_ability)
    @db_expiry_time = ApplicationHelper.db_expiry_time
  end
end

app/views/data/_bulk_download.html.haml
:javascript
  $(document).ready(function() {

    $('.bulk_data_notifications').hide();

    $(function() {
      $("#startpicker").datepicker();
      $("#startpicker").datepicker('setDate', new Date());
    });

    $(function() {
      $("#endpicker").datepicker();
      $("#endpicker").datepicker('setDate', new Date());
    });


    function send_download_url(datatype) {
      var startdate = $("#startpicker").datepicker("getDate");
      var enddate   = $("#endpicker"  ).datepicker("getDate");
      enddate.setDate(enddate.getDate() + 1);

      var ids = [];
      $('#instrument_ids_:checked').each(function() {
        ids.push($(this).attr('value'));
      });

      var site_fields = [];
      $('#site_fields_:checked').each(function() {
        site_fields.push($(this).attr('value'));
      });

      var instrument_fields = [];
      $('#instrument_fields_:checked').each(function() {
        instrument_fields.push($(this).attr('value'));
      });

      var var_fields = [];
      $('#var_fields_:checked').each(function() {
        var_fields.push($(this).attr('value'));
      });


      if (startdate < enddate) {
        var url = '';
        url += '/data/create_bulk_download';

        //document.location.href = url;
        $.post(
          url,
          { 
            start: startdate.toISOString(),
            end: enddate.toISOString(),
            instruments: ids.join(),
            include_test_data: $('#include_test_data').is(":checked"),
            site_fields: site_fields.join(),
            instrument_fields: instrument_fields.join(),
            var_fields: var_fields.join()
          }, // data to be submit
          function(data, status, jqXHR) {// success callback
            $('.bulk_data_notifications').html('Your bulk download is now being created. Please reload this page to check its status.');
            $('.bulk_data_notifications').show();
          })        
      } else {
        alert("Start date must be less than or equal to the end date");
      }
    };

    $('.bulkDownloadButton').click(function(){
      $('.bulk_data_notifications').html('... Initiating CSV Package Creation (this takes a minute - please wait) ...');
      $('.bulk_data_notifications').show();

      send_download_url('geojson');
    });


    $('#select_all').click(function(){
      $('.instrument-select-checkbox').each(function() {
        this.checked = true;
      });
    });

    $('#select_none').click(function(){
      $('.instrument-select-checkbox').each(function() {
        this.checked = false;
      });
    });



    

  });




%h2.text-center 
  Create New Bulk Download Package
%h4.text-center
  (Zipped csv format)
%table.table
  %tbody

    %tr{:align => "center"}
      %td{:colspan => 4}
        %p
          %span
            = check_box_tag 'include_test_data', 'include_test_data', true
            %strong
              Include Test Data
        %p

        %button.btn-primary.bulkDownloadButton Create Bulk Data Download (zipped csv)
        %p
        The creation of the file can take a long time depending on system resouces and runs in the background.
        %p

        .bulk_data_notifications.alert.alert-success


    %tr{:align => "center"}
      %td
        %b
          Start Date (start of day)

        #startpicker
        %p

        %b
          End Date (end of day)

        #endpicker
      %td
        %p Select instruments for download. If none are checked, all instruments will be downloaded.

        %table.table.table-striped
          %thead
            %tr
              %th
                Select for
                %br
                Download
              %th Instrument Name
              %th Site
              %th
                Available
                %br
                Measurements
          %tbody
            - @instruments.each do |instrument|
              %tr
                %td= check_box_tag 'instrument_ids[]', instrument.id, true, class: 'instrument-select-checkbox'
                %td= link_to(instrument.name, instrument_url(:id => instrument.id) )
                %td= @sites.find(instrument.site_id).name
                %td= instrument.sample_count(:either)

        %p
          %button#select_all Select All
          %button#select_none Clear All


      %td
        %p Select colums to include

        %b
          Site Fields

        %table.table.table-striped
          %thead
            %tr
              %th
                Include
              %th Field Name
          %tbody
            - BulkDownload.site_fields.each do |field, checked|
              %tr
                %td= check_box_tag 'site_fields[]', field, checked
                %td= field


        %b
          Instrument Fields

        %table.table.table-striped
          %thead
            %tr
              %th
                Include
              %th Field Name
          %tbody
            - BulkDownload.instrument_fields.each do |field, checked|
              %tr
                %td= check_box_tag 'instrument_fields[]', field, checked
                %td= field


        %b
          Var Fields

        %table.table.table-striped
          %thead
            %tr
              %th
                Include
              %th Field Name
          %tbody
            - BulkDownload.var_fields.each do |field, checked|
              %tr
                %td= check_box_tag 'var_fields[]', field, checked
                %td= field




  

app/views/data/_download_by_day.html.haml
:javascript
  $(document).ready(function() {
    $(function() {
      $("#startpicker").datepicker();
      $("#startpicker").datepicker('setDate', new Date());
    });

    $(function() {
      $("#endpicker").datepicker();
      $("#endpicker").datepicker('setDate', new Date());
    });


    function send_download_url(datatype) {
      var startdate = $("#startpicker").datepicker("getDate");
      var enddate   = $("#endpicker"  ).datepicker("getDate");
      enddate.setDate(enddate.getDate() + 1);

      var ids = [];
      $('#instrument_ids_:checked').each(function() {
        ids.push($(this).attr('value'));
      });

      if (startdate < enddate) {
        var url = '';
        url += '/api/v1/data.' + datatype + '?';
        url += 'start=' + startdate.toISOString();
        url += '&end='  + enddate.toISOString();

        if (ids.length > 0) {
          url += '&instruments=' + ids.join();
        }

        if ($('#include_test_data').is(":checked")) {
          url += '&include_test_data=' + $('#include_test_data').is(":checked");
        }

        document.location.href = url;
      } else {
        alert("Start date must be less than or equal to the end date");
      }
    };

    $('.geoJsonButton').click(function(){
      send_download_url('geojson');
    });

    $('.geoCsvButton').click(function(){
      send_download_url('csv');
    });

    $('#select_all').click(function(){
      $(':checkbox').each(function() {
        this.checked = true;
      });
    });

    $('#select_none').click(function(){
      $(':checkbox').each(function() {
        this.checked = false;
      });
    });



    

  });

%h2 Download Data By Day
%table.table
  %thead
    %tr{:align => "center"}
      %td{:align => "center"} Start Date (start of day)
      %td{:align => "center"} End Date (end of day)
  %tbody
    %tr{:align => "center"}
      %td
        #startpicker
      %td
        #endpicker
%br/

%p
  %button#select_all Select All
  %button#select_none Clear All
  %button.btn-primary.geoJsonButton Download GeoJSON
  %button.btn-primary.geoCsvButton Download GeoCSV
%p
  %span
    = check_box_tag 'include_test_data'

    %strong
      Include Test Data in Download

%p Select instruments for download. If none are checked, all instruments will be downloaded. It is generally recommended to download a month of data at a time. If you select a date range resulting in too much data, you will receive an error message. Reduce the date range selected and try again.

%table.table.table-striped
  %thead
    %tr
      %th
        Select for
        %br
        Download
      %th Instrument Name
      %th Site
      %th
        Available
        %br
        Measurements
      %th
        Fetch/
        %br
        Ingest Data
  %tbody
    - @instruments.each do |instrument|
      %tr
        %td= check_box_tag 'instrument_ids[]', instrument.id
        %td= link_to(instrument.name, instrument_url(:id => instrument.id) )
        %td= @sites.find(instrument.site_id).name
        %td= instrument.sample_count(:either)
        %td= link_to 'Data URLs', data_urls_about_index_path(instrument_id: instrument.id)

%p
  %button#select_all Select All
  %button#select_none Clear All
  %button.btn-primary.geoJsonButton Download GeoJSON
  %button.btn-primary.geoCsvButton Download GeoCSV

%p
  See the
  %i Data URLs
  for URL syntax definitions used to make customized data ingest and download
  requests. These URLs are also used for program generated requests, e.g from browsers, Matlab, R, Python, etc.

app/views/data/_trim.html.haml
-# This functionality is deprecated, becuase data deletion is not feasible with 
-# influxdb. It may be useful later with other types of datastore.
:javascript
  $(document).ready(function() { 
  
  	$(function() {
  		$("#trimpicker").datepicker({
  			altField: "#end",
  			altFormat: "yy-mm-dd"
  		});
  	});
  
  
  	$( "#trim_data_form" ).submit(function( event ) {
  
  		var trimdate = $("#trimpicker").datepicker("getDate");
  
      var radios = document.getElementsByName('trim_id');
      var labels = document.getElementsByName('instrument_radio_label');
      var trim_id = "";
      var trim_name = "";
  
      for (var i = 0, length = radios.length; i < length; i++) {
          if (radios[i].checked) {
              // get the radio button value and label text
              trim_id = radios[i].value;
              trim_name = labels[i].innerHTML;
              // only one radio can be logically checked, don't check the rest
              break;
          }
      }
      
  		if (trim_id == "") {
    		alert ("You must select an instrument.");
  		} else {
    		var minDays = 5;
    		var oldest = new Date();
    		oldest.setDate(oldest.getDate() - minDays);
    		if (trimdate > oldest) {
    			var msg = trimdate + "\nis too recent.\nYou must retain at least " + minDays + " days of data.";
    			alert(msg);
    			event.preventDefault();
    		} else {
    			var now = new Date();
    			var days = Math.floor((now - trimdate) / (1000 * 60 *60 * 24));
    			var msg = "Are you sure that you want to erase data before\n" + trimdate + ",\n"
    			if (trim_id == "all") {
            msg = msg + "for ALL instruments? ";
    			} else {
            msg = msg + "for instrument " + trim_name + "? ";
          }
    			msg = msg + "This is " + days + " days ago.";
    
    			var response = confirm(msg);
    			if (response == false) {
    				event.preventDefault();
    			}
    		}
  		}
  	});
  
  });
%h2 Trim Database
%p
  Remove all measurements before this date from the database.
%p
  %strong Use this carefully. It will permanently erase data from your database!
%table.table
  %thead
    %tr
      %td{:align => "center"} End Date (from the start of this day)
  %tbody
    %tr
      %td
        #trimpicker{:align => "center"}
    = form_tag(measurements_trim_path, :method => 'post', :id => 'trim_data_form') do
      %tr
        %td{:align => "center"}
          .instrumentstrip
            .instrumentstatus
              = radio_button_tag(:trim_id, "all", :checked=>true)
              = label_tag(:trim_id, "All", name: 'instrument_radio_label')
            - @instruments.each do |instrument|
              .instrumentstatus
                = radio_button_tag(:trim_id, instrument.id)
                = label_tag(:trim_id, instrument.name, name: 'instrument_radio_label')
      %tr
        %td{:align => "center"}
          = hidden_field_tag('end')
          = submit_tag("Erase Data!", :id => 'trim_data_submit')

app/views/data/bulk_download.html.haml
%h1 Bulk Data Download


%p
Space left on system hard drive:
%b
	= number_to_human_size @space_left_on_system

%p
Total size of all bulk data packages (Includes temporary files):
%b
	= number_to_human_size Dir["#{BulkDownload.tmp_dir}/**/*"].select { |f| File.file?(f) }.sum { |f| File.size(f) }


- if @bulk_download_files.count > 0 || @placeholder_files.count > 0
	%h3.text-center
		Existing Downloads
	%table.table.table-striped
		%thead
			%tr
				%th
					Name
				%th 
					Creation Date
				%th 
					File Size
				%th
					Actions 
		%tbody
			- @bulk_download_files.each do |bulk_download_file|				  
				%tr
					%td
						= File.basename bulk_download_file
					%td
						= File::ctime bulk_download_file
					%td
						- compressed_file_size = File.size bulk_download_file
						= number_to_human_size compressed_file_size
					%td
						
						= link_to 'Download', "/data/send_bulk_download_file?file=#{File.basename bulk_download_file}"
						&nbsp;&nbsp;&nbsp;

						= link_to "Delete", "/data/delete_bulk_download_file?file=#{File.basename bulk_download_file}", method: "delete", data: {confirm: "Are you sure you want to permanently delete #{File.basename bulk_download_file}?"} 

			- @placeholder_files.each do |placeholder_file|				  
				%tr
					%td
						= File.basename placeholder_file
					%td
						= File::ctime placeholder_file
					%td
						(creation in progress)
					%td

	.text-center
		Please note that some systems can have difficulty unzipping files using their native software. 
		%br
		On OSX if you have trouble unzipping these archives, consider using 
		= link_to "The Unarchiver", 'https://theunarchiver.com/'
		instead.



= render partial: "bulk_download"

app/views/data/index.html.haml
%h1 Data Functions
%p
  Observations prior to
  %b= @db_expiry_time
  are automatically removed from the database.

- if @profile.data_archive_url?
  %p
    Archived data may be found at:
    = link_to nil, @profile.data_archive_url

%p
  Bulk data download is available at:
  %b= link_to 'Bulk Download', bulk_download_path


= render partial: "download_by_day"