config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  root to: 'dashboard#index', constraints: lambda { |request| Profile.first && !Profile.first.secure_data_viewing }
  root to: 'about#index', as: :unauthenticated_root

  namespace :api, :defaults => {format: 'json'} do
    namespace :v1 do
      resources :sites
      resources :data, only: [:index, :show]
    end
  end

  get '/bulk_download'            , to: 'bulk_download#index'
  get '/bulk_download/download'  , to: 'bulk_download#download'
  delete '/bulk_download/delete'  , to: 'bulk_download#destroy'
  post '/bulk_download'           , to: 'bulk_download#create'

  resources :dashboard
  resources :data, only: :index
  resources :influxdb_tags
  resources :linked_data, only: [:index, :edit, :update, :show]
  resources :measured_properties
  resources :site_types
  resources :topic_categories
  resources :units

  

  resources :about, only: :index do
    collection do
      get :data_urls
    end
  end

  resources :instruments do
    member do
      get :live
    end

    collection do
      get :duplicate
      get :live
      get :simulator
    end
  end

  resources :measurements, except: [:index, :show, :new, :create, :update, :edit, :destroy] do
    collection do
      get  :url_create
      post :delete_test
    end
  end

  resources :monitor do
    collection do
      get :live
    end
  end

  resources :profiles, only: [:index, :create, :backup, :restore] do
    collection do
      get :export_configuration
      get :import_configuration
      post :import_configuration

      get :export_influxdb
      get :import_influxdb
      post :import_influxdb

      post :test_sending_email
    end
  end

  resources :sites do
    collection do
      get :map
      get :map_markers_geojson
    end

    member do
      get :map_balloon_json
    end
  end

  resources :users do
    get :assign_api_key
  end

  resources :vars do
    collection do
      get :autocomplete_measured_property_label
      get :autocomplete_unit_name
    end
  end

end

app/models/instrument.rb
class Instrument < ApplicationRecord
  include Rails.application.routes.url_helpers

  belongs_to :site

  has_many :vars, dependent: :destroy
  has_many :influxdb_tags, dependent: :destroy

  belongs_to :topic_category

  accepts_nested_attributes_for :vars

  def self.initialize
  end

  def to_s
    name
  end

  def select_label
    "#{site.name}: #{name}"
  end

  def find_var_by_shortname (shortname)
    var_id = Var.all.where("instrument_id='#{self.id}' and shortname='#{shortname}'").pluck(:id)[0]

    if var_id
      return Var.find(var_id)
    else
      return nil
    end
  end

  # Returns the time of first or last measurement given parameter point ("first" or "last")
  def point_time_in_ms(point)
    if point == "last"
      latest_point = GetLastTsPoint.call(TsPoint, 'value', self.id)
    else
      latest_point = GetFirstTsPoint.call(TsPoint, 'value', self.id)
    end

    if(defined? latest_point.to_a.first['time'])
      latest_time_ms = Time.parse(latest_point.to_a.first['time'])
    else
      latest_time_ms = "None"
    end

    return latest_time_ms
  end

  # get the downsampling rate for influx query
  def downsample_rate (starttime, endtime, var_id)
    max_points = self.maximum_plot_points

    if endtime == nil
      count = TsPoint \
        .count("value") \
        .where(inst: self.id) \
        .where(var: var_id) \
        .since(starttime)
    else
      count = TsPoint \
        .count("value") \
        .where(inst: self.id) \
        .where(var: var_id) \
        .where(time: starttime..endtime)
    end

    if count.to_a.nil? || count.to_a.empty?
        return self.sample_rate_seconds
    end

    num_points = count.to_a[0]["count"].to_i

    if num_points > max_points
      rate = (num_points.to_f / max_points).ceil * self.sample_rate_seconds
      return rate
    else
      return self.sample_rate_seconds
    end
  end

  # return the maximum number of points per variable to render => 180
  # TODO: add option for user input when setting env variables
  def maximum_plot_points
    return 180
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names

      all.each do |rails_model|
        csv << rails_model.attributes.values_at(*column_names)
      end
    end
  end

  def self.data_insert_url
    url = instrument_url()
  end

  def is_receiving_data
    if defined? TsPoint
      return IsTsInstrumentAlive.call(TsPoint, "value", self.id, self.sample_rate_seconds+5)
    else
      return false
    end
  end

  def last_age
    if defined? TsPoint
      return GetLastTsAge.call(TsPoint, "value", self.id)
    else
      return false
    end
  end

  def sample_count(sample_type)
    case sample_type
    when :not_test
      measurement_count
    when :test
      measurement_test_count
    else
      measurement_count + measurement_test_count
    end
  end

  def refresh_rate_ms
    # Limit the chart refresh rate
    if self.sample_rate_seconds >= 1
      refresh_rate_ms = self.sample_rate_seconds*1000
    else
      refresh_rate_ms = 1000
    end

    return refresh_rate_ms
  end

  def influxdb_tags_hash
    influxdb_tags = Hash.new

    self.influxdb_tags.each do |influxdb_tag|
      influxdb_tags[influxdb_tag.name] = influxdb_tag.value
    end

    return influxdb_tags
  end

  def instrument_url
    p = Profile.first
    link = p.domain_name + "/instruments/" + self.id.to_s
    return link
  end

  def current_day_download_link(type)
    '/api/v1/data/' + self.id.to_s + ".#{type.to_s}"
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  load_and_authorize_resource

  before_action :set_instrument, only: [:show, :live]

 # GET /instruments/1/live?var=varshortname&after=time
 # Return measurements and metadata for a given instrument, var and time period.
 # Limit the number of points returned to the instrument's display_points value.
  def live
    # Verify the parameters
    # convert the millisecond input to seconds since epoch
    if ((defined? params[:after]) && (params[:after].to_i != 0))
      start_time_ms = Time.strptime(params[:after], '%Q')
    else
      time_offset = "#{@instrument.plot_offset_value}.#{@instrument.plot_offset_units}"
      start_time_ms = @instrument.point_time_in_ms("last") - eval(time_offset)
    end

    livedata = {
                 points: [],
                 multivariable_points: {},
                 multivariable_names: [],
                 display_points: 0,
                 refresh_msecs: 1000
               }

    livedata[:display_points] = @instrument.maximum_plot_points
    livedata[:refresh_msecs] = @instrument.refresh_rate_ms

    # If the var parameter is set, then we build and return data for only this variable.
    if (params[:var])
      variable = @instrument.find_var_by_shortname(params[:var])

      # Fetch the data
      live_points = variable.get_tspoints(start_time_ms)

      if live_points
      livedata[:points] = live_points
      end

    # otherwise we return data for all variables
    else
      @instrument.vars.each do |variable|
        livedata[:multivariable_names] << variable.shortname
        livedata[:multivariable_points][variable.shortname] = []

        # Fetch the data
        live_points = variable.get_tspoints(start_time_ms)

        if live_points
          livedata[:multivariable_points][variable.shortname] = live_points
        end
      end
    end

    render json: ActiveSupport::JSON.encode(livedata)
  end


  # GET instruments/simulator
  def simulator
    if @profile.secure_data_entry && current_user.api_key.blank?
      flash[:notice] = 'An API Key is necessary to use the simulator. Please add one by editing the user in the Users section.'
    end

    if @profile.secure_data_entry && (current_user.role?(:admin) || current_user.role?(:site_config))
      flash[:alert] = 'Admin and Site Config users cannot create measurements, please sign in as a regular user with the Measurements ability enabled.'
    end

    @sites = Site.all     # if group permissions ever applied, this should be used Site.accessible_by(current_ability)
    @instruments = Instrument.all   # if group permissions ever applied, this should be used Instrument.accessible_by(current_ability)
  end

  # GET /instruments/duplicate?instrument_id=1
  # TODO: should be GET /instruments/[INSTRUMENT_ID]/duplicate?number_of_duplicates=[num_dups]
  def duplicate
    old_instrument = Instrument.accessible_by(current_ability).find(params[:instrument_id])
    num_dups = params[:number_of_duplicates].to_i

    if old_instrument && num_dups > 0
      num_dups.times do
        # Make a copy
        # TODO: note this is shallow copy...make sure that is valid in this context
        #       should do this in a transaction as well
        new_instrument = old_instrument.dup
        new_instrument.sensor_id = nil  # this value is unique, so we can't clone it

        if !new_instrument.name.include? "clone"
          new_instrument.name = new_instrument.name + " clone"
        end

        new_instrument.last_url = nil

        # Create duplicates of the vars
        old_instrument.vars.each do |v|
          new_var = v.dup
          new_var.save
          new_instrument.vars << new_var
        end

        new_instrument.save
      end
    end

    redirect_to instruments_path
  end

  def index
    @sites = Site.accessible_by(current_ability)
  end

  def show
    # This method sets the following instance variables:
    #  @var_to_plot    - The variable currently being plotted
    #  @tz_name        - the timezone name
    #  @tz_offset_mins - the timezone offset, in minutes
    #  @last_url       - the last url
    @last_url = InstrumentsHelper.sanitize_url(GetLastUrl.call(TsPoint, @instrument.id))

    # Get the timezone name and offset in minutes from UTC.
    @tz_name, @tz_offset_mins = ProfileHelper::tz_name_and_tz_offset

    # Set the variable to plot
    if params[:var_id]
      @var_to_plot = Var.find(params[:var_id])
    else
      if (defined? @instrument.vars.first.id)
        @var_to_plot = Var.find(@instrument.vars.first.id)
      end
    end

    # Determine the time range. Default to the most recent day
    end_time = Time.now
    start_time = end_time - 1.day

    if params.key?(:last)
      start_time = @instrument.point_time_in_ms("last")
      end_time = start_time
    else
      # See if we have the start and end parameters
      if params.key?(:start)
        start_time = Time.parse(params[:start])
      end

      if params.key?(:end)
        end_time = Time.parse(params[:end])
      end
    end

    # Get the time series points from the database
    ts_points  = GetTsPoints.call(TsPoint, "value", @instrument.id, start_time, end_time)

    respond_to do |format|
      format.html

      format.sensorml do
        topic_category = @instrument.topic_category ? @instrument.topic_category.name : ''

        render file: "app/views/instruments/sensorml.xml.haml", layout: false, locals: { topic_category: topic_category }
      end
    end
  end

  def new
  end

  def create
    if @instrument.sensor_id.blank?
      @instrument.sensor_id = nil
    end

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    data = instrument_params

    if data[:sensor_id].blank?
      data[:sensor_id] = nil
    end

    respond_to do |format|
      if @instrument.update(data)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @instrument.destroy
        format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :show, alert: 'Instrument could not be destroyed!' }
        format.json { render @instrument.errors, status: :bad_request }
      end
    end
  end

private
  def set_instrument
    # using a where.first clause prevents an exception being thrown if the instrument is not present or not visible to the user
    @instrument = if !params[:sensor_id].blank?
                    Instrument.accessible_by(current_ability).where(sensor_id: params[:sensor_id]).first
                  else
                    nil
                  end

    if @instrument.nil?
      @instrument = Instrument.accessible_by(current_ability).where(id: params[:id]).first
    end

    @instrument
  end

  def instrument_params
    params.require(:instrument).permit(:name, :site_id, :is_active, :display_points, :sample_rate_seconds, :description,
                                       :instrument_id, :plot_offset_value, :plot_offset_units, :topic_category_id,
                                       :sensor_id, :number_of_duplicates)
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
  def self.sanitize_url(url)
    # Sanitize a url by obscuring the security key in the url.
    return '' unless url

    # Look for the key terminated by "&"
    re = /key=.+&/

    new_url = if re.match(url)
                url.gsub(re, 'key=hidden&')
              else
                # Look for key at the end of the url
                re = /key=.+/

                if re.match(url)
                  url.gsub(re, 'key=hidden')
                else
                  ''
                end
              end

    return new_url.html_safe
  end

  def put_data_url
    url = url_for(only_path: false, host: request.host, controller: 'measurements', action: 'url_create', instrument_id: @instrument.id)

    @instrument.vars.each do |var|
      url +=  "&#{var.shortname}=#{var.name}"
    end

    url += "&at=2015-08-20T19:50:28"
    url += "&email=[USER_EMAIL]&api_key=[API_KEY]"
    url += "&test"
    return url
  end

  def put_data_url_with_sensor_id
    url = "#{root_url}measurements/url_create?sensor_id=#{@instrument.sensor_id}"

    @instrument.vars.each do |var|
      url +=  "&#{var.shortname}=#{var.name}"
    end

    url += "&at=2015-08-20T19:50:28"
    url += "&email=[USER_EMAIL]&api_key=[API_KEY]"
    url += "&test"
    return url
  end

  def data_file_download_url(file_extension, range = nil)
    url = url_for(only_path: false, host: request.host, controller: 'api/v1/data', action: :show, id: @instrument.id)
    url += ".#{file_extension}"

    if range
      url += "?"
    end

    if range == 'last'
      url += "last"
    elsif range == 'start_end'
      url += "start=2015-08-01T00:30&end=2015-08-20T12:30"
    end

    return url
  end

  def multi_inst_data_file_download_url(file_extension, range = nil, ids = nil, test_data = false, auth = false)
    url = url_for(only_path: false, host: request.host, controller: 'api/v1/data', action: :index)
    url += ".#{file_extension}" if file_extension

    if range || ids || test_data || auth
      url += "?"
    end

    case ids
    when 'sensors'
      url += 'sensors=sen1,sen2,sen3'
    when 'instruments'
      url += 'instruments=1,2,3'
    end

    if ids && range
      url += '&'
    end

    case range
    when 'start_end'
      url += "start=2015-08-01T00:30&end=2015-08-20T12:30"
    end

    if test_data
      url += '&' if (range || ids)
      url += 'test'
    end

    if auth
      url += '&' if (range || ids || test_data)
      url += "email=[USER_EMAIL]&api_key=[API_KEY]"
    end

    return url
  end

  # =>  return js for use in simulator
  def create_instrument_variables_js(instruments)
    js_lines = Array.new

    instruments.each do |instrument|
      js_lines.push("var instrument_#{instrument.id}_run_status = false;")
      js_lines.push("var instrument_#{instrument.id}_shortnames = [];")

      instrument.vars.each do |var|
        js_lines.push("instrument_#{instrument.id}_shortnames.push(\"#{var.shortname}\");")
      end
    end


    return js_lines.join("\n")
  end

  def get_security_key_url_fragment
    url_fragment = ''

    # add the security key
    if @profile.secure_data_entry == true
      begin
        url_fragment = "&email=" + current_user.email + "&api_key=" + current_user.api_key
      rescue TypeError
        url_fragment = "&email=" + current_user.email + "&api_key=[INSERT_API_KEY]"
      end
    end

    return url_fragment.html_safe
  end

end

app/views/instruments/_form.html.haml
= form_for(@instrument, html: {class: "new_or_edit_form" }) do |f|
  - if @instrument.errors.any?
    #error_explanation
      %h2
        = pluralize(@instrument.errors.count, "error")
        prohibited this instrument from being saved:
      %ul
        - @instrument.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :sensor_id, "Sensor ID"
    %br/
    = f.text_field :sensor_id, class: 'form-control'
  .field
    = f.label :is_active, 'Active'
    &nbsp;
    = f.check_box :is_active
  .field
    = f.label :topic_category
    %br/
    = f.collection_select :topic_category_id, TopicCategory.order(:name),:id,:name, include_blank: false
  .field
    = f.label :description
    %br/
    = f.text_area :description, class: 'form-control'
  .field
    = f.label :site
    %br/
    = f.collection_select :site_id, Site.order(:name),:id,:name, include_blank: false
  .field
    = f.label :display_points
    %br/
    = f.text_field :display_points, class: 'form-control'
    %br/
  .field
    = f.label :plot_offset
    %br/
    = f.text_field :plot_offset_value, :default => '1', class: 'form-control'
    = f.select(:plot_offset_units,  { years: 'years', months: 'months', weeks: 'weeks', days: 'days', hours: 'hours', minutes: 'minutes', seconds: 'seconds' }, :selected => :weeks)


    %br/
  .field
    = f.label :sample_rate_seconds
    %br/
    = f.text_field :sample_rate_seconds, class: 'form-control'
  .field
    %br
    %br
    %b Variables
    %div.row
      %div.col-lg-10.col-md-11
        .row-fluid
          .col-sm-1
            - if can?(:create, Var) && params[:action] == 'edit'
              %br
              = link_to 'Add New Variable', new_var_path(instrument_id: @instrument.id, return: 'edit'), class: 'btn btn-default btn-md', style: 'text-decoration: none; color: black;', title: 'Add New Variable'
              %br
              %br
        %table.table.table-striped
          %tr
            %th Name
            %th Short Name
            %th Units
            %th Abbreviation
            %th Measured Property

          - @instrument.vars.each do |v|
            %tr
              %td= v.name
              %td= v.shortname
              %td= v.unit.try(:name)
              %td= v.unit.try(:abbreviation)
              %td= v.measured_property.try(:label)
              %td.col-sm-1= link_to '', edit_var_path(v, return: 'edit'), class: 'glyphicon glyphicon-pencil', style: 'text-decoration: none; color: black;', title: 'Edit'
              %td.col-sm-1= link_to '', v, method: :delete, data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-trash', style: 'text-decoration: none; color: black;', title: 'Delete'

  .actions
    = f.submit class: 'btn btn-md btn-primary'

app/views/instruments/_graph.html.haml
- if (@var_to_plot)

  .instrumentstrip
    Graph:
    - @instrument.vars.each do |v|
      = link_to v.name, instrument_path(@instrument, var: v.shortname, var_id: v.id)


  - # Easier to read double quote
  - quote = "\""

  - # Create the highcharts data series for a single variable
  - series = "[{name:\"#{@var_to_plot.name}\""", data: []}]"

  - # Convert items containing quotes into suitable json
  - series         = series.as_json.html_safe

  - # Craft a title for the chart
  - title = quote + "#{@instrument.name}: #{@var_to_plot.name} - Live Data" + quote
  - title  = title.as_json.html_safe

  #instrument_live_chart.instrument_highchart{:style => "min-width: 310px; height: 400px; margin: 0 auto"}
    = render 'multivariable_graph_chart', series: series, title: title

app/views/instruments/_instrument_measurements.haml
%h4
  Measurements
= @instrument.sample_count(:either)
measurements were reported.
- if @instrument.sample_count(:test) > 0
  = "#{@instrument.sample_count(:test)} of these are test values."
  .delete_test_measurements_form
    = render partial: "delete_test_measurements_form", locals: {instrument: @instrument}
%br
This instrument is expected to report a measurement every
= @instrument.sample_rate_seconds
seconds.
%br
- if @instrument.point_time_in_ms("first") != "None"
  = "The first measurement was measured at #{@instrument.point_time_in_ms("first")}."
  %br
  = "The last measurement is #{@instrument.last_age} old. It was measured at #{@instrument.point_time_in_ms("last")}."

app/views/instruments/_instrument_variables.haml
.clear
%h4
  Variables

.row-fluid
  .col-sm-1
    - if can? :create, Var
      = button_to 'Add New Variable', new_var_path, params: {instrument_id: @instrument.id}, method: :get, class: 'btn btn-default btn-md'
      %br

.clear


%table.table.border
  %tr
    %td
      Short Name
    %td
      Name
    %td
      = link_to 'Units', :units
    %td
      Min/Max (Plot)
    %td
      = link_to 'Measured Property', :measured_properties

    %td
      &nbsp;

    - @instrument.vars.each do |variable|
      %tr.border
        %td
          = variable.shortname

        %td
          = variable.name

        %td
          = variable.unit.try(:name)
          %br
          = variable.unit.try(:abbreviation)



        %td
          = variable.minimum_plot_value
          \/
          = variable.maximum_plot_value


        %td
          = variable.measured_property.try(:label)

        %td.col-sm-1
          - if can?(:edit, variable)
            = link_to '', edit_var_path(variable), class: 'glyphicon glyphicon-pencil', style: 'text-decoration: none; color: black;', title: 'Edit'
        %td.col-sm-1
          - if can?(:destroy, variable)
            = link_to '', variable, method: :delete, data: {confirm: "Are you sure you want to permanently delete the variable #{variable.name} and all associated data?"}, class: 'glyphicon glyphicon-trash', style: 'text-decoration: none; color: black;'

app/views/instruments/_monitor.html.erb
<% 
 highcharts_dom_id = "highcharts_instrument_#{@instrument.id}"
 
 if @varshortname != nil 
   # Determine the selected variable full name
   varname = @varnames[@varshortname]
   # Easrier to read doulble quote
   quote = "\""
   # Create the highcharts data series for a single variable
   series = "[{name:" + quote + varname + quote + ", data: [" + @instrument.data(@instrument.display_points, @varshortname) + "]}]"
   # Craft a title for the chart
   title = quote + @instrument.name + ": " + varname + " - Live Data"+quote
   # Convert items containing quotes into suitable json
   series = series.as_json.html_safe
   title = title.as_json.html_safe 
%>

<div class="instrument_highchart" id="<%= highcharts_dom_id %>" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<%= render 'monitor_chart', highcharts_dom_id: highcharts_dom_id, series: series, title: title, varname: @varnames[@varshortname], varshortname: @varshortname %>

<% end %>

app/views/instruments/edit.html.haml
%h1 Editing Instrument
%br
%div.row
  %div.col-lg-8.col-md-10
    = render 'form'
%br
= link_to 'Show', @instrument
|
= link_to 'Back', instruments_path

app/views/instruments/index.html.haml
%h1 Instruments

- if can?(:create, Instrument)
  - if @sites.count > 0
    = button_to 'New Instrument', new_instrument_path, method: :get, class: 'btn btn-default btn-md'
  - else
    %strong At least one site must be defined before creating a new instrument.

.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th{align: "center"} Status
        %th{align: "center"} Name
        %th{align: "center"} Active
        %th{align: "center"} Id
        %th{align: "center"} Sensor Id
        %th{align: "center"} Active
        %th{align: "center"}
          Interval
          %br>/
          (s)
        %th{align: "center"}
          Last
          %br>/
          Measurement
        %th{align: "center"} Site
        %th{align: "center"}
          \# of
          = succeed "Variables" do
            %br/
        %th{align: "center"}
          \# of
          = succeed "Measurements" do
            %br/

        - if can?(:download, Instrument) || can?(:create, :measurement)
          %th{align: "center"}
            Fetch/Ingest
            %br>/
            Data
          %th{colspan: "1"}
    %tbody
      - @instruments.each do |instrument|
        %tr
          %td{align: "center"}
            - if instrument.is_receiving_data
              = image_tag('button_green_50.png', size:"16")
            - else
              = image_tag('button_red_50.png', size:"16")
          %td
            = link_to(instrument.name, instrument_url(id: instrument.id) )
          %td
            = instrument.is_active
          %td
            = instrument.id
          %td
            = instrument.sensor_id
          %td{align: "center"}
            - if instrument.is_active
              = "Yes"
            - else
              = "No"

          %td{align: "center"}= instrument.sample_rate_seconds
          %td= instrument.last_age
          %td= link_to(@sites.find(instrument.site_id).name, site_url(@sites.find(instrument.site_id).id))
          %td{align: "center"}= instrument.vars.count
          %td{align: "center"}= instrument.sample_count(:either)

          - if can?(:download, Instrument) || can?(:create, :measurement)
            %td{align: "center"}= link_to 'Data URLs', data_urls_about_index_path(instrument_id: instrument.id)

          - if can?(:create, Instrument)
            %td.col-sm-1
              = form_tag(duplicate_instruments_path, method: :get, id: "duplicate_instrument_form_#{instrument.id}") do
                = select_tag "number_of_duplicates", options_for_select((1..100).to_a , "1")
                copies
                = hidden_field_tag('instrument_id', instrument.id)
                &nbsp;
                = button_tag type: :submit, title: 'Duplicate', class: 'transparent_button' do
                  %span.glyphicon.glyphicon-duplicate

          - if can?(:delete_test, :measurement)
            %td= render partial: "delete_test_measurements_form", locals: { instrument: instrument }

          %td
            - if can?(:edit, instrument)
              = link_to '', edit_instrument_path(instrument), class: 'glyphicon glyphicon-pencil', style: 'text-decoration: none; color: black;', title: 'Edit'
          %td
            - if can?(:destroy, instrument)
              = link_to '', instrument, method: :delete, class: 'glyphicon glyphicon-trash', style: 'text-decoration: none; color: black;', title: 'Delete', |
                data: { confirm: "Are you sure you want to delete the \n#{instrument.name} at #{@sites.find(instrument.site_id).name}?\n\nTHE INSTRUMENT AND ALL DATA WILL BE PERMANENTLY DELETED" }

- if can?(:create, Instrument)
  - if @sites.count > 0
    = button_to 'New Instrument', new_instrument_path, method: :get, class: 'btn btn-default btn-md'
  - else
    %strong At least one site must be defined before creating a new instrument.

%h2 Identifiers

%button.collapsed{"aria-expanded" => "false", "data-target" => "#summarytable", "data-toggle" => "collapse", type: "button", class: 'btn btn-default btn-md'}
  Show Details For Grafana Setup

#summarytable.table-responsive.collapse
  %table.table.table-striped
    %thead
      %tr
        %th
          Site
          %br>/
          Name
        %th
          Instrument
          %br>/
          Name
        %th
          Variable
          %br>/
          Name
        %th
          Variable
          %br>/
          Short
          %br>/
          Name
        %th
          Site
          %br>/
          Id
        %th
          Instrument
          %br>/
          Id
        %th
          Variable
          %br>/
          Id
      %tbody
        - @sites.each do |site|
          - site.instruments.each do |instrument|
            - instrument.vars.each do |var|
              %tr
                %td=site.name
                %td=instrument.name
                %td=var.name
                %td=var.shortname
                %td=site.id
                %td=instrument.id
                %td=var.id

app/views/instruments/new.html.haml
%h1 New Instrument
%div.row
  %div.col-lg-8.col-md-10
    = render 'form'
%br
= link_to 'Back', instruments_path

app/views/instruments/show.html.haml
- if @last_url.presence
  .last_url
    = @last_url
.instrument_name
  - if @instrument.is_receiving_data
    = image_tag('button_green_50.png', size:"16")
  - else
    = image_tag('button_red_50.png', size:"16")

  = @instrument.name
  = "(id: #{@instrument.id})"

  - if !@instrument.sensor_id.blank?
    = "(sensor_id: #{@instrument.sensor_id})"
  - else
    = "(sensor_id: n/a)"

  located at
  = @instrument.site.name

.instrument_description
  Description:
  = @instrument.description
  %br
  This instrument is designated as:
  - if @instrument.is_active
    = "ACTIVE"
  - else
    = "INACTIVE"
  %br
  (If 'INACTIVE', the instrument will not appear in the dashboard.)

%br
- if can? :edit, @instrument
  = button_to 'Edit Instrument', edit_instrument_path(@instrument), method: :get, class: 'btn btn-primary btn-md'
  %br

.instrument_configuration
  .left
    .instrument_measurements
      = render partial: "instrument_measurements", locals: {instrument: @instrument}

  .right
    - if can?(:download, @instrument)
      .instrument_download
        = render partial: "instrument_downloads", locals: {instrument: @instrument}

.clear
%br
%br

.instrument_plot_time_window
  .left
    %strong Plot measurements for the last
    %strong= @instrument.plot_offset_value.to_s + " " + @instrument.plot_offset_units.to_s

= (render 'multivariable_graph').html_safe

.clear
%br

.full_width
  .instrument_variables
    = render partial: "instrument_variables", locals: {instrument: @instrument}

%br
= link_to 'Back', instruments_path